# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""
Generate per-letter Luau word list modules from SCOWL source files.

Usage:
    uv run tools/generate_wordlist.py [--size 80]
    uv run tools/generate_wordlist.py --size 50   # smaller list

Prereqs:
    tools/scowl/final/   -- SCOWL pre-built word files (see README below)
    tools/wordlists/offensive.txt  -- one word per line blocklist

Download SCOWL (one-time):
    curl -L "https://sourceforge.net/projects/wordlist/files/SCOWL/2020.12.07/scowl-2020.12.07.tar.gz/download" -o tools/scowl/scowl.tar.gz
    tar -xzf tools/scowl/scowl.tar.gz -C tools/scowl --strip-components=1

Output:
    src/shared/Dictionary/words/{a..z}.luau  -- 26 packed-string modules
"""

import argparse
import re
import sys
from pathlib import Path

# Two-letter words to preserve even though they're below the length floor.
TWO_LETTER_ALLOWLIST = frozenset(
    "am an as at be by do go he if in is it me my no of on or ok so to up us we".split()
)

# Only include words from these SCOWL locale families.
# Covers American + British spellings (colour/color, organise/organize).
# Excludes Canadian, Australian, and less-common regional variants.
INCLUDED_LOCALES = frozenset(
    ["english", "american", "british", "british_z"]
)

LUAU_HEADER_TMPL = (
    "--!strict\n"
    "-- AUTO-GENERATED by tools/generate_wordlist.py — do not edit by hand.\n"
    "-- Re-run: uv run tools/generate_wordlist.py --size {size}\n"
)


def load_offensive(path: Path) -> frozenset[str]:
    if not path.exists():
        print(f"Warning: offensive list not found at {path} — skipping filter", file=sys.stderr)
        return frozenset()
    words: set[str] = set()
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        w = line.strip().lower()
        if w and not w.startswith("#"):
            words.add(w)
    print(f"Loaded {len(words)} offensive-filter words", file=sys.stderr)
    return frozenset(words)


def _resolve_final_dir(scowl_dir: Path) -> Path:
    """Find the SCOWL final/ directory, tolerating common extraction layouts."""
    # Standard: tools/scowl/final/
    candidate = scowl_dir / "final"
    if candidate.is_dir():
        return candidate
    # Tarball extracted with strip-components=1: files directly in scowl_dir
    # Check if *.words.* files are directly here
    if any(scowl_dir.glob("*.words.*")):
        return scowl_dir
    # Tarball NOT stripped: tools/scowl/scowl-2020.12.07/final/
    for sub in scowl_dir.iterdir():
        if sub.is_dir():
            deep = sub / "final"
            if deep.is_dir():
                return deep
    return candidate  # return the expected path so the error message is useful


def _file_size(filename: str) -> int | None:
    """Extract the trailing size number from a SCOWL filename, or None."""
    m = re.search(r"\.(\d+)$", filename)
    return int(m.group(1)) if m else None


def _should_include(filename: str, size_cap: int) -> bool:
    """True if this file's words should be included at the given size cap.

    SCOWL 2020 naming: {locale}-{type}.{size}
    We want only plain {locale}-words.{N} files where:
      - locale is in INCLUDED_LOCALES
      - N <= size_cap
    """
    name = filename.lower()
    # Only plain word files — excludes proper-names, upper, abbreviations, contractions
    m = re.match(r"^([a-z_]+)-words\.(\d+)$", name)
    if not m:
        return False
    locale, size_str = m.group(1), m.group(2)
    if locale not in INCLUDED_LOCALES:
        return False
    return int(size_str) <= size_cap


def collect_words(final_dir: Path, size_cap: int) -> set[str]:
    if not final_dir.is_dir():
        print(
            f"Error: SCOWL final/ directory not found at {final_dir}\n"
            "Download and extract SCOWL first — see script docstring.",
            file=sys.stderr,
        )
        sys.exit(1)

    words: set[str] = set()
    files_read = 0

    for f in sorted(final_dir.iterdir()):
        if not f.is_file():
            continue
        if not _should_include(f.name, size_cap):
            continue
        files_read += 1
        for line in f.read_text(encoding="utf-8", errors="replace").splitlines():
            w = line.strip()
            if not w:
                continue
            # Drop contractions (apostrophes in any form)
            if "'" in w or "’" in w:
                continue
            words.add(w.lower())

    if files_read == 0:
        print(
            f"Error: no SCOWL source files matched in {final_dir}\n"
            "Check that the SCOWL archive was extracted correctly.",
            file=sys.stderr,
        )
        sys.exit(1)

    print(f"Read {files_read} SCOWL source files → {len(words)} raw words", file=sys.stderr)
    return words


def filter_words(words: set[str], offensive: frozenset[str]) -> set[str]:
    result: set[str] = set()
    skipped_short = skipped_offensive = skipped_nonalpha = 0

    for w in words:
        # Length guard — allow short words only from explicit allowlist
        if len(w) <= 2 and w not in TWO_LETTER_ALLOWLIST:
            skipped_short += 1
            continue
        # Offensive filter
        if w in offensive:
            skipped_offensive += 1
            continue
        # Only plain ASCII letters (no hyphens, digits, accented chars)
        if not re.match(r"^[a-z]+$", w):
            skipped_nonalpha += 1
            continue
        result.add(w)

    print(
        f"Filtered: kept {len(result)} | "
        f"dropped short={skipped_short} offensive={skipped_offensive} non-alpha={skipped_nonalpha}",
        file=sys.stderr,
    )
    return result


def split_by_letter(words: set[str]) -> dict[str, list[str]]:
    buckets: dict[str, list[str]] = {chr(ord("a") + i): [] for i in range(26)}
    for w in words:
        first = w[0]
        if first in buckets:
            buckets[first].append(w)
    for lst in buckets.values():
        lst.sort()
    return buckets


def write_luau_files(buckets: dict[str, list[str]], out_dir: Path, size_cap: int) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    header = LUAU_HEADER_TMPL.format(size=size_cap)
    total = 0

    for letter in sorted(buckets):
        words = buckets[letter]
        total += len(words)
        # Long-string literal: Luau strips the first newline after [[, so words start
        # at index 0 with no leading blank entry when parsed by gmatch("[^\n]+").
        packed = "\n".join(words)
        content = header + "return [[\n" + packed + "\n]]\n"
        out_path = out_dir / f"{letter}.luau"
        out_path.write_text(content, encoding="utf-8")
        print(f"  {letter}.luau  {len(words):>6} words", file=sys.stderr)

    print(f"\nTotal: {total} words written to {out_dir}", file=sys.stderr)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate per-letter Luau word list modules from SCOWL."
    )
    parser.add_argument(
        "--size", type=int, default=60,
        help="SCOWL size cap — include words from files with size ≤ this value (default: 60)",
    )
    parser.add_argument(
        "--scowl-dir", default="tools/scowl",
        help="Root of extracted SCOWL archive (default: tools/scowl). "
             "Note: size refers to SCOWL's non-cumulative size files. "
             "Size 60 ≈ 80k words; size 80 ≈ 250k words.",
    )
    parser.add_argument(
        "--out-dir", default="src/shared/Dictionary/words",
        help="Output directory for .luau files (default: src/shared/Dictionary/words)",
    )
    parser.add_argument(
        "--offensive", default="tools/wordlists/offensive.txt",
        help="Path to offensive word blocklist (default: tools/wordlists/offensive.txt)",
    )
    args = parser.parse_args()

    scowl_dir = Path(args.scowl_dir)
    out_dir = Path(args.out_dir)
    offensive_path = Path(args.offensive)

    offensive = load_offensive(offensive_path)
    final_dir = _resolve_final_dir(scowl_dir)
    raw_words = collect_words(final_dir, args.size)
    filtered = filter_words(raw_words, offensive)
    buckets = split_by_letter(filtered)
    write_luau_files(buckets, out_dir, args.size)


if __name__ == "__main__":
    main()
